### ISSUE TITLE
Add super simple lib

### ISSUE THREAD

**Issue by TheAngryByrd** [TheAngryByrd/MiniScaffold#109]
Miniscaffold might be too much, let's have a super simple lib version available that just supplies paket, fake 5 and class lib with a simple structure

https://twitter.com/k_cieslak/status/1040606250332037121

**Comment by baronfel** [comment]
or possibly keep all the features and add `--no-FEATURE` toggles for the big/high-impact ones?

**Comment by TheAngryByrd** [comment]
I like it in theory but that might get too difficult to maintain, and also might be difficult for a user to know what giant string of things to turn off would be.

**Comment by ominestre** [comment]
Thread necromancy here but what about something that is similar to the interactivity in Yeoman where you can toggle the features you want.

https://github.com/yeoman/yo/blob/master/screenshot.png

**Comment by TheAngryByrd** [comment]
It would be whatever dotnet templating's feature set supports.  I don't wanna get into the business of building my own templating engine.

**Comment by TheAngryByrd** [comment]
https://github.com/giraffe-fsharp/giraffe-template and https://github.com/SAFE-Stack/SAFE-template are two of the more complex templates I know of as examples of what can be done

**Comment by TheAngryByrd** [comment]
Now that https://ionide.io/Libraries/waypoint.html exists, we probably don't need this
