### ISSUE TITLE
dotnet new -i "MiniScaffold::*" doen't work

### ISSUE THREAD

**Issue by DieselMeister** [TheAngryByrd/MiniScaffold#126]
Hi. 

I am trying to generate a template, but the installation doesn't work (checked on 2 Computers).
The template doesn't appear in my template list and if I try to generate one I get the message, that the template doesn't exists.

Can someone reproduce this?

btw. I get no error message while try to install.

**Comment by TheAngryByrd** [comment]
Hmm somethings wrong with the latest nuget package.  In the meantime you can do `dotnet new -i "MiniScaffold::0.14.0`

**Comment by TheAngryByrd** [comment]
Fixed in #127
