### ISSUE TITLE
Remove the weird local tools hack when .net core 3.0 comes out

### ISSUE THREAD

**Issue by TheAngryByrd** [TheAngryByrd/MiniScaffold#134]
## Description

Currently we have this weird hack around dotnet core notion of tools.  We don't want to pollute someones machine with global tools because different versions may be an issue.  Now that .net 3.0 supports local tools we should just use this.

https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#local-tools

## Error messages, screenshots

Please add any error logs or screenshots if available.

## Failing test, failing github repo, or reproduction steps

Please add either a failing test, a github repo of the problem or detailed reproduction steps.

## Expected Behavior

Please define what you would expect the behavior to be like.

## Known workarounds

Please provide a description of any known workarounds.

## Other information

* Operating System:
    - [ ] windows [insert version here]
    - [ ] macOs [insert version]
    - [ ] linux [insert flavor/version here]
* Platform
    - [ ] dotnet core
    - [ ] dotnet full
    - [ ] mono
* Branch or release version:

**Comment by TheAngryByrd** [comment]
https://gist.github.com/baronfel/80f49ecb93ebacb84ca840fca7a12fc2 for an example

**Comment by baronfel** [comment]
paket may be a bad example, as I was chatting with steffen and krzysztof and they want to clean up the global tool install to just be the magic-mode bootstrapper (which hardly ever changes) and you'd add your paket version as the first line of your `paket.dependencies`

**Comment by TheAngryByrd** [comment]
Ok i'll skip paket/fake for now but this will work for fantomas, sourcelink, and reportgenerator-cli.

**Comment by TheAngryByrd** [comment]
This is done
