### ISSUE TITLE
Consider replacing netfx.props with Microsoft.NETFramework.ReferenceAssemblies package

### ISSUE THREAD

**Issue by atlemann** [TheAngryByrd/MiniScaffold#140]
There is now a meta-package for building full framework targets on linux/mac. It's still in preview though, but seems to work:

Microsoft.NETFramework.ReferenceAssemblies

You could consider replacing the `netfx.props` workaround with this package instead.

**Comment by TheAngryByrd** [comment]
https://github.com/dotnet/sdk/issues/335#issuecomment-530293809 for additional reference
