### ISSUE TITLE
Consider adding CI through GitHub Actions

### ISSUE THREAD

**Issue by rojepp** [TheAngryByrd/MiniScaffold#143]
Out of the box support for GitHub Actions would be wonderful. Now GHA is not out of beta yet, but it will be released this year.

- [x] Build MiniScaffold w/ Actions
- [ ] Include Actions in templates

**Comment by TheAngryByrd** [comment]
https://github.community/t5/GitHub-Actions/Refusing-to-allow-an-integration-to-create-or-update/td-p/32472 

This causing me to be unable to push to other branches now 😭
