### ISSUE TITLE
Consider dropping support for full framework

### ISSUE THREAD

**Issue by TheAngryByrd** [TheAngryByrd/MiniScaffold#169]
**Is your feature request related to a problem? Please describe.**

We should consider dropping support for full framework entirely. It can be a burden for library authors to maintain multiple TFMs. Also later versions of full framework can consume netstandard2.0.

**Describe the solution you'd like**

Drop support for net461 and add back in netstandard2.0.

Removes the need for mono on linux builds as well.

**Describe alternatives you've considered**

Currently there's documentation [to remove full framework](https://www.jimmybyrd.me/MiniScaffold/How_Tos/Remove_Full_Framework.html) if desired.

**Additional context**

**Comment by ImaginaryDevelopment** [comment]
could it be a distinct template that supports full framework?

**Comment by TheAngryByrd** [comment]
With no more major versions of full coming out and everything going to be `.NET 5`,  I don't want to have the burden of supporting it. If people need to support it, adding the TFM is not difficult.

**Comment by rmunn** [comment]
If this is implemented, the docs for [removing the full framework](https://www.jimmybyrd.me/MiniScaffold/How_Tos/Remove_Full_Framework.html) should be supplemented with docs for adding it back in, for anyone who still needs it and isn't already intimately familiar with the process.
