### ISSUE TITLE
Generate API docs for free-floating dlls

### ISSUE THREAD

**Issue by baronfel** [TheAngryByrd/MiniScaffold#173]
**Is your feature request related to a problem? Please describe.**
I'd like a mods of the documentation generator that lets me specify a dll + optional xml docs file and generate just the reference docs.  I used a previous version of the docs generate to generate FSharp.Core docs (https://baronfel.github.io/fsharp-core-api-docs/) as kind of a community service thing, but the styling/UX of those pages is lacking and newer doctool efforts don't support this use case.

**Describe alternatives you've considered**
Wailing and gnashing of teeth.

**Comment by TheAngryByrd** [comment]
@baronfel can you give me an repro of that so I can get a head start on it? Thanks.

**Comment by TheAngryByrd** [comment]
I think this works as of https://github.com/TheAngryByrd/MiniScaffold/pull/222
