### ISSUE TITLE
Directory.Build.props in src/ and tests/ needs to import top-level props file

### ISSUE THREAD

**Issue by rmunn** [TheAngryByrd/MiniScaffold#176]
**Describe the bug**
According to https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2019#use-case-multi-level-merging, once MSBuild finds one `Directory.Build.props` file, it stops looking further up the directory tree. So once it finds the `Directory.Build.props` file in either `src` or `tests`, it will stop there and not climb up to the top-level directory of the project. To get it to also include the props defined in the top-level directory, the MS docs say the following line should be added to `src/Directory.Build.props` and `tests/Directory.Build.props`:

```xml
<Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />
```

No repro steps because I haven't had time (yet) to test this and verify that it's an actual bug. The documentation seems pretty clear about it, though.

**Comment by baronfel** [comment]
This is a real thing, good find @rmunn. The dotnet/fsharp repo does this same pattern in places and it took me a while to figure out why.
