### ISSUE TITLE
Change coverage file pattern

### ISSUE THREAD

**Issue by halcwb** [TheAngryByrd/MiniScaffold#191]
**Is your feature request related to a problem? Please describe.**
When porting an existing library to the MiniScaffold template, I ran into a problem with generating a coverage report. I had added a new test project with just one framework setting. This generates a coverage xml like `coverage.xml`, instead of for example: `coverage.net461.xml`. However, with a name like `coverage.xml`, this is not picked up by the `GenerateCoverageReport` target.

**Describe the solution you'd like**
If you change the file glob pattern from `!!"tests/**/coverage.*.xml"` to `!!"tests/**/coverage*.xml"` then it works also in my scenario. (So, I just removed the `.`).

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by TheAngryByrd** [comment]
Nice catch! Feel free to send a pull request 😀

**Comment by halcwb** [comment]
Thanks, I will.
