### ISSUE TITLE
My docs won't build!?

### ISSUE THREAD

**Issue by blair55** [TheAngryByrd/MiniScaffold#202]
## Description

I'm trying to add documentation to the library I've just published using MiniScaffold.

I've created a new markdown file here: docsSrc/How_Tos/my_how_to.md

The markdown file contains example F# source code.

However, it seems this code is being compiled... 🤯

The problem is that the code includes a reference to a third party library using an `open` directive. The library has been added to the src project and behaves as expected.

But when running `./build.sh BuildDocs` the job fails because the compiler cannot identify the namespace, and I don't know how to tell it where to look?

I've tried using paket to add the library to the docsTool project but that hasn't resolved the issue.

How do I fix this? Thanks!

```
Fatal error: System.Exception: error while formatting file /Users/nblair/work/DynamoDb.Ok/docsSrc/How_Tos/Write_an_item.md. Errors are:
seq
  [SourceError
     ((3, 5),(3, 11),Error,"The namespace or module 'Amazon' is not defined.");
...
```

## Other information

* Operating System:
    - [ ] windows [insert version here]
    - [x] macOs [Catalina]
    - [ ] linux [insert flavor/version here]
* Platform
    - [x] dotnet core
    - [ ] dotnet full
    - [ ] mono
* Branch or release version: latest

**Comment by TheAngryByrd** [comment]
Is there a repro I can look at?

**Comment by blair55** [comment]
Sure, its this repo

https://github.com/totallymoney/DynamoDb.Ok

**Comment by TheAngryByrd** [comment]
I have a fix, I'll be making PR to here and your project later today.

Giving F# compiler all the correct flags is a fun puzzle :)

**Comment by blair55** [comment]
Thanks for fixing!

Do what steps can I follow to pull this fix into my repo?

Or would it be easier just to recreate now?
