### ISSUE TITLE
Regarding the 'standard .gitignore'

### ISSUE THREAD

**Issue by halcwb** [TheAngryByrd/MiniScaffold#206]
**Is your feature request related to a problem? Please describe.**
For some time I am using an opt-in approach regarding .gitignore files. This makes sure I never ever by accident will add unnecessary or even private information to github. 

**Describe the solution you'd like**
What I want is that you have to be explicit about what you will commit to git. I wonder whether this is something that could be used for MiniScaffold as well?

**Describe alternatives you've considered**
I use the following structure:

```
# Ignore all files using an opt-inn approach
*

# Add .gitignore and .gitattributes
!.gitignore
!.gitattributes

# Add license
!LICENSE.txt

# Add todo list
!ToDo.txt

# Add md files
!*.md

# Add fsx files
!*.fsx

# Add build files
!build.sh
!build.cmd

# Etc ...

```

**Comment by TheAngryByrd** [comment]
While I really do like this idea, I'm unsure I'd like to push something this specific on the user-base. 

I have been considering allowing for more modification using flags but I also have to worry about maintainability of the template.  I'm going to keep this open as a potential use case for having multiple options when creating the template.
