### ISSUE TITLE
Cannot rerun DotnetTest

### ISSUE THREAD

**Issue by halcwb** [TheAngryByrd/MiniScaffold#208]
**Is your feature request related to a problem? Please describe.**
I cannot rerun the DotnetTest target. I then get:

> _Saved' exists from a previous run.  Either manually examine and delete it, or run with '/p:AltCoverForce=true' to force deletion 

I wonder why this is? 

**Describe the solution you'd like**
I have added the following line to the AltCover command line arguments:

"/p:AltCoverForce=true"

**Comment by TheAngryByrd** [comment]
This sounds like an issue that should be opened in the [AltCover repo](https://github.com/SteveGilham/altcover).

**Comment by TheAngryByrd** [comment]
Hmm yeah I can't reproduce this locally on my mac.  Sounds like an issue to open on AltCover repo.
