### ISSUE TITLE
Why pin to specific versions

### ISSUE THREAD

**Issue by halcwb** [TheAngryByrd/MiniScaffold#209]
**Is your feature request related to a problem? Please describe.**
I noticed that in the dependencies file you pin libs to specific versions. I have a lib depending on FSharp.Core 4.7.1 This  I don't get working trying to port to MiniScaffold. 

**Describe the solution you'd like**
I would like it to be easier to port existing libs with dependencies to MiniScaffold. Currently it works wel when starting a new lib or console app using the pinned dependencies, however, this is limiting the usability.

**Describe alternatives you've considered**
I tried getting things working using paket update. This didn't succeed.

**Comment by TheAngryByrd** [comment]
It's pinned to make it easier to keep from the transitive dependencies going out of control.  If you need to relax constraints, you can just remove the pins or reduce the pinned versions as you need for each project. If you're relaxing constraints and paket isn't working correctly, you should open an issue there on the [paket repo](https://github.com/fsprojects/Paket).

**Comment by halcwb** [comment]
Isn't it the paket lock file that is making sure that this doesn't happen? 

Anyways good to know, when upgrading you can get into this problem: https://andrewlock.net/fixing-the-error-program-has-more-than-one-entry-point-defined-for-console-apps-containing-xunit-tests/.

So, suddenly the main entry point method complains that it is no longer the last line in the project. Fixed with the above mentioned article.

**Comment by halcwb** [comment]
To further elaborate with this, after a lot of trail and error I came up with this working checklist:

# Changing to MiniScaffold

- [ ] Get the latest Github version of your lib.

- [ ]  Create a clone in a different folder (as backup).

- [ ]  Remove all files and directories from your lib folder.

- [ ]  Run `dotnet new mini-scaffold` in your lib folder.

- [ ]  Update the `paket.dependencies` folder.

Use these additions:

```
framework: auto-detect
redirects: on
```
remove the pinned versions from:
- FSharp.Core
- All the Fake libs

Add your own lib dependencies

- [ ] Update the `paket.reference` files with you own dependencies.

- [ ]  Change the .net versions.

Change to netstandard2.1, netcoreapp3.1; net472

##### Lib proj

        <TargetFrameworks>netstandard2.1;net472</TargetFrameworks>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>


##### Test proj

        <TargetFrameworks>netcoreapp3.1</TargetFrameworks>
        <GenerateProgramFile>false</GenerateProgramFile>

Note that the `GenerateProgramFile<false>` is because when updating the test runners 
result in this issue: https://andrewlock.net/fixing-the-error-program-has-more-than-one-entry-point-defined-for-console-apps-containing-xunit-tests/

- [ ]  Change the `build.fsx`.

Make sure that FSharp.Core is ignored and force removal of temp AltCover folders.

```
let dotnetTest ctx =
    let excludeCoverage =
        !! testsGlob
        |> Seq.map IO.Path.GetFileNameWithoutExtension
        // ignore FSharp.Core
        |> Seq.append ["FSharp.Core"]
        |> String.concat "|"
    
    let args =
        [
            "--no-build"
            // Make sure temp folder is removed
            "/p:AltCoverForce=true"
            sprintf "/p:AltCover=%b" (not disableCodeCoverage)
            sprintf "/p:AltCoverThreshold=%d" coverageThresholdPercent
            sprintf "/p:AltCoverAssemblyExcludeFilter=%s" excludeCoverage
        ]
    DotNet.test(fun c ->

        { c with
            Configuration = configuration (ctx.Context.AllExecutingTargets)
            Common =
                c.Common
                |> DotNet.Options.withAdditionalArgs args
            }) sln

```

Disable the anayzers target
```
// Issue: https://github.com/ionide/FSharp.Analyzers.SDK/issues/22
//    ==> "FSharpAnalyzers"
```

You might also need to lower the `coverageThresholdPercent` to a lower setting.

- [ ] Update dependencies.

```
dotnet tool restore
dotnet paket update
```

- [ ] Fix problem in the docsTool.

```
    let openBrowser url =
        let waitForExit (proc : Process) =
            proc.WaitForExit()
            if proc.ExitCode <> 0 then printfn "opening browser failed"
```

So a `printfn` instead of `failwith`.

- [ ] Update the `.travis.yml`

`dotnet: 3.1`

- [ ] Move the content of the `RELEASE_NOTES.md` to the `CHANGELOG.md`

- [ ] Make sure that the `Assembly.info` files contain the right names and entries

- [ ] Use an opt-in approach in the `.gitignore` file.

You can check in Visual Studio in the folders view which files will be add to the repository.

- [ ] Run `/build.sh` or `build.cmd`.

**Comment by TheAngryByrd** [comment]
> Isn't it the paket lock file that is making sure that this doesn't happen?

Sorry I wasn't clear on that.  The lock file only fixes that issue during restore time. However when you update a dependency, paket will always take the highest version in that transitive chain. Which has caused issues for me in the past with regards to Microsoft libraries only liking certain runtimes. (hopefully this kind of stuff will settle down around .NET 5).  [The resolver strategy docs](https://fsprojects.github.io/Paket/dependencies-file.html#Resolver-strategy-for-transitive-dependencies) covers this a bit more.  The problem with setting things to min/max is there's no in between.  Pinning is the only real other option here.  I could probably relax a few of these but during development letting the transitives get out of control has caused really bizarre issues I couldn't track down.

**Comment by halcwb** [comment]
#

> > Isn't it the paket lock file that is making sure that this doesn't happen?
> 
> Sorry I wasn't clear on that. The lock file only fixes that issue during restore time. However when you update a dependency, paket will always take the highest version in that transitive chain. Which has caused issues for me in the past with regards to Microsoft libraries only liking certain runtimes. (hopefully this kind of stuff will settle down around .NET 5). [The resolver strategy docs](https://fsprojects.github.io/Paket/dependencies-file.html#Resolver-strategy-for-transitive-dependencies) covers this a bit more. The problem with setting things to min/max is there's no in between. Pinning is the only real other option here. I could probably relax a few of these but during development letting the transitives get out of control has caused really bizarre issues I couldn't track down.

Thanks, very clear, I will close this issue.
