### ISSUE TITLE
Watch Docs fails out of the box

### ISSUE THREAD

**Issue by halcwb** [TheAngryByrd/MiniScaffold#211]
**Describe the bug**
When creating an out of the box lib with mini-scaffold and try to run ./build WatchDocs, this fails. More or less like issue #183 but now it fails right away.

**To Reproduce**
1. Make a new lib dir like OriginalScaffold
2. Run the template with dotnet new mini-scaffold
3. Try to start up WatchDocs with ./build WatchDocs
4. The browser opens with the docs, but then is unresponsive because:

> watch : Exited
> watch : Waiting for a file to change before restarting dotnet...
> Created disposable directory C:\Users\halcw\AppData\Local\Temp\1f54aafc765c47f39ed30f1c4ec63ebc
> Generating API Docs for C:\Development\lab\OriginalScaffold\src\OriginalScaffold\bin\Debug\netstandard2.1\OriginalScaffold.dll
> Rendering C:\Development\lab\OriginalScaffold\docsSrc\index.md
> Rendering C:\Development\lab\OriginalScaffold\docsSrc\Explanations\Background.md
> Rendering C:\Development\lab\OriginalScaffold\docsSrc\files\placeholder.md
> Rendering C:\Development\lab\OriginalScaffold\docsSrc\How_Tos\Doing_Another_Thing.md
> Rendering C:\Development\lab\OriginalScaffold\docsSrc\How_Tos\Doing_A_Thing.md
> Rendering C:\Development\lab\OriginalScaffold\docsSrc\Tutorials\Getting_Started.md
> Rendered to C:\Users\halcw\AppData\Local\Temp\1f54aafc765c47f39ed30f1c4ec63ebc\index.html
> Rendered to C:\Users\halcw\AppData\Local\Temp\1f54aafc765c47f39ed30f1c4ec63ebc\Explanations\Background.html
> Rendered to C:\Users\halcw\AppData\Local\Temp\1f54aafc765c47f39ed30f1c4ec63ebc\files\placeholder.html
> Rendered to C:\Users\halcw\AppData\Local\Temp\1f54aafc765c47f39ed30f1c4ec63ebc\How_Tos\Doing_Another_Thing.html
> Rendered to C:\Users\halcw\AppData\Local\Temp\1f54aafc765c47f39ed30f1c4ec63ebc\How_Tos\Doing_A_Thing.html
> Rendered to C:\Users\halcw\AppData\Local\Temp\1f54aafc765c47f39ed30f1c4ec63ebc\Tutorials\Getting_Started.html
> Rendered to C:\Users\halcw\AppData\Local\Temp\1f54aafc765c47f39ed30f1c4ec63ebc\Api_Reference\OriginalScaffold\OriginalScaffold.html
> Rendered to C:\Users\halcw\AppData\Local\Temp\1f54aafc765c47f39ed30f1c4ec63ebc\Api_Reference\OriginalScaffold\originalscaffold-say.html
> Rendered to C:\Users\halcw\AppData\Local\Temp\1f54aafc765c47f39ed30f1c4ec63ebc\Api_Reference\OriginalScaffold\originalscaffold-say-favoritecolor.html
> Rendered to C:\Users\halcw\AppData\Local\Temp\1f54aafc765c47f39ed30f1c4ec63ebc\Api_Reference\OriginalScaffold\originalscaffold-say-person.html
> Hosting environment: Production
> Content root path: C:\Development\lab\OriginalScaffold\docsTool\bin\Debug\netcoreapp3.1\
> Now listening on: http://localhost:5000
> Application started. Press Ctrl+C to shut down.
> Unhandled exception. System.Exception: opening browser failed
>    at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1637.Invoke(String message) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\printf.fs:line 1637
>    at Program.WebServer.waitForExit@537.Invoke(Process proc) in C:\Development\lab\OriginalScaffold\docsTool\Program.fs:line 538
>    at Program.WebServer.openBrowser(String url) in C:\Development\lab\OriginalScaffold\docsTool\Program.fs:line 548
>    at Program.WebServer.serveDocs@561.Invoke(Unit unitVar) in C:\Development\lab\OriginalScaffold\docsTool\Program.fs:line 562
>    at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 398
>    at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 109
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.FSharp.Control.AsyncPrimitives.Start@907-1.Invoke(ExceptionDispatchInfo edi) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 907
>    at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 109
>    at Microsoft.FSharp.Control.TrampolineHolder.ExecuteWithTrampoline(FSharpFunc`2 firstAction) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 177
>    at <StartupCode$FSharp-Core>.$Async.-ctor@163-1.Invoke(Object o) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 165
>    at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
>    at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
>    at System.Threading.QueueUserWorkItemCallback.Execute()
>    at System.Threading.ThreadPoolWorkQueue.Dispatch()
>    at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
> watch : Exited with error code -532462766
> watch : Waiting for a file to change before restarting dotnet...

**Expected behavior**
Changing a file should restart the server, but nothing happens.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser IE

**Comment by halcwb** [comment]
I just changed the failwith to a printfn which resolves the problem:

`             if proc.ExitCode <> 0 then printfn "opening browser failed"
`

**Comment by TheAngryByrd** [comment]
Ugh this one keeps coming up.  Different platforms open the browsers slightly differently and it's frustrating.
