### ISSUE TITLE
Cannot publis to  nuget

### ISSUE THREAD

**Issue by halcwb** [TheAngryByrd/MiniScaffold#212]
**Describe the bug**
When I try the PublishToNuget target this fails. Also, when I try do this by hand using the paket add-token command this doesn't run:

```
c:\Development\lab\OriginalScaffold\dist>dotnet paket config add-token https://www.nuget.org  <MYAPIKEY>
Paket version 5.241.2
Performance:
 - Runtime: 372 milliseconds

c:\Development\lab\OriginalScaffold\dist>dotnet paket push OriginalScaffold.0.1.0.nupkg --verbose
Paket version 5.241.2
Pushing package OriginalScaffold.0.1.0.nupkg to https://nuget.org/api/v2/package - trial 1
No authorization found in config file.
Request failed with '403': 'https://www.nuget.org/api/v2/package'
Response body was:
Could not push OriginalScaffold.0.1.0.nupkg: Request to 'https://www.nuget.org/api/v2/package' failed with: 403 Forbidden - The specified API key is invalid, has expired, or does not have permission to access the specified package.

```

**To Reproduce**
1. Create a new lib using the template
2. Add the nuget API key as is described
3. Try to run the PublishToNuget target.

**Expected behavior**
Publishing of the package.

Obviously this is a paket issue, but I wonder whether you have run into this as well.

**Comment by TheAngryByrd** [comment]
Hmm I think paket needs the "key" to be the same as the target. Can you try adding your key as `https://www.nuget.org/api/v2/package` ?

**Comment by TheAngryByrd** [comment]
Or I guess "source" is the better term here since you're adding a api key as a value...

**Comment by halcwb** [comment]
Also, using `https://www.nuget.org/api/v2/package` doesn't work. I created an issue in the paket repository: https://github.com/fsprojects/Paket/issues/3843.

**Comment by halcwb** [comment]
A workaround in the build script is this code:

```fsharp
let publishToNuget _ =
    allReleaseChecks ()
    let apikey = Environment.environVarOrDefault "API_KEY" ""
    if apikey = "" then    
        Paket.push(fun c ->
            { c with
                ToolType = ToolType.CreateLocalTool()
                PublishUrl = publishUrl
                WorkingDir = "dist"
            }
        )
    else
        Paket.push(fun c ->
            { c with
                ToolType = ToolType.CreateLocalTool()
                PublishUrl = publishUrl
                WorkingDir = "dist"
                ApiKey = apikey
            }
        )
        
    // If build fails after this point, we've pushed a release out with this version of CHANGELOG.md so we should keep it around
    Target.deactivateBuildFailure "RevertChangelog"

```

So you can now run the target with `API_KEY=<myapikey> ./build.sh PublishToNuget <version_number>`

**Comment by TheAngryByrd** [comment]
I was able to push a package recently.  Definitely sounds like a misconfiguration.  

However it makes sense to have this as an environment variable as well similar to the `GITHUB_TOKEN`
