### ISSUE TITLE
After release, changes of the changelog and assembly info aren't committed and pushed.

### ISSUE THREAD

**Issue by halcwb** [TheAngryByrd/MiniScaffold#229]
**Describe the bug**
When running the release target, the local repository contains the updated changelog, but this isn't pushed to the origin.

**To Reproduce**
1. run the release target
2. check with git status, you'll get for example:

> λ git status                                                                        
> On branch master                                                                    
> Your branch is up to date with 'origin/master'.                                     
>                                                                                     
> Changes to be committed:                                                            
>   (use "git restore --staged <file>..." to unstage)                                 
>         modified:   CHANGELOG.md                                                    
>         modified:   src/Informedica.Utils.Lib/AssemblyInfo.fs                       
>                                                                                     
> Changes not staged for commit:                                                      
>   (use "git add <file>..." to update what will be committed)                        
>   (use "git restore <file>..." to discard changes in working directory)             
>         modified:   docs/coverage/Informedica.Utils.Lib_App.htm                     
>         modified:   docs/coverage/Informedica.Utils.Lib_Array.htm                   
>         modified:   docs/coverage/Informedica.Utils.Lib_BigRational.htm             
>         modified:   docs/coverage/Informedica.Utils.Lib_Char.htm                    
>         modified:   docs/coverage/Informedica.Utils.Lib_Continuation.htm            
>         modified:   docs/coverage/Informedica.Utils.Lib_DateTime.htm                
>         modified:   docs/coverage/Informedica.Utils.Lib_Double.htm                  
>         modified:   docs/coverage/Informedica.Utils.Lib_File.htm                    
>         modified:   docs/coverage/Informedica.Utils.Lib_Int32.htm                   
>         modified:   docs/coverage/Informedica.Utils.Lib_List.htm                    
>         modified:   docs/coverage/Informedica.Utils.Lib_Memoization.htm             
>         modified:   docs/coverage/Informedica.Utils.Lib_NullCheck.htm               
>         modified:   docs/coverage/Informedica.Utils.Lib_Option.htm                  
>         modified:   docs/coverage/Informedica.Utils.Lib_Path.htm                    
>         modified:   docs/coverage/Informedica.Utils.Lib_Reflection.htm              
>         modified:   docs/coverage/Informedica.Utils.Lib_Seq.htm                     
>         modified:   docs/coverage/Informedica.Utils.Lib_String.htm                  
>         modified:   docs/coverage/index.htm                                         
>         modified:   docs/coverage/main.js                                           
>         modified:   tests/Informedica.Utils.Tests/AssemblyInfo.fs           

        

**Expected behavior**
Together with the released package, the remote repository should be updated as well.

**Comment by TheAngryByrd** [comment]
Can you ensure `GitRelease` target ran?

https://github.com/TheAngryByrd/MiniScaffold/blob/12b351f1b8eca3d28f24e94662b387b880d0e5bb/Content/Library/build.fsx#L570-L587

**Comment by halcwb** [comment]
@TheAngryByrd Yeah, I think it runs. But I will keep you posted. Didn't release anything recently.

**Comment by TheAngryByrd** [comment]
Going to close, please re-open if this happens again
