### ISSUE TITLE
Fix repo description (says net5.0, in readme it's net6.0)

### ISSUE THREAD

**Issue by delneg** [TheAngryByrd/MiniScaffold#253]

**Comment by pramod74** [comment]
Hi @delneg,

I would like to give it a shot. Can you please let me know the files where the update is required to be made?

**Comment by makeProjectGreatAgain** [comment]
I assume only maintainers can edit **About** section in the GitHub repository

**Comment by pramod74** [comment]
OK. Thanks for the update.

**Comment by TheAngryByrd** [comment]
Done!
