### ISSUE TITLE
Incorrect release guide on github pages

### ISSUE THREAD

**Issue by PolinaSavelyeva** [TheAngryByrd/MiniScaffold#284]
**Describe the bug**
The steps to add NUGET_TOKEN from https://www.jimmybyrd.me/MiniScaffold/Tutorials/Getting_Started_With_Libraries.html#Add-your-NUGET_TOKEN-to-your-environment are incorrect. 

**Expected behavior**
"[Create an Environment](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#creating-an-environment) on your repository named nuget." should be "Add your NuGet API key as repository secret NUGET_TOKEN to [Actions secrets](https://github.com/PolinaSavelyeva/RoomInteriorGenerator/settings/secrets/actions)", as it mentioned in the project's README.

**Comment by TheAngryByrd** [comment]
It’s the other way around. The readme is incorrect.  Would you like to send a PR to fix this?

**Comment by PolinaSavelyeva** [comment]
I've just checked the latest library template and still got error message while following steps described on pages. 

```
Could not push package /home/runner/work/Test/Test/dist/MyCoolNewLib.1.0.0.nupkg due to missing credentials 
for the url https://www.nuget.org/api/v2/package. Please specify a NuGet API key via the command line, the 
environment variable "nugetkey", or by using 'paket config add-token'.
```
Using Repository secrets instead of Environment secrets fixes the issue. If I understood correctly, i would like to send a PR.
