### ISSUE TITLE
Move to .NET 8.0

### ISSUE THREAD

**Issue by simon-reynolds** [TheAngryByrd/MiniScaffold#287]
Hello @TheAngryByrd 

I've got a local version of MiniScaffold updated to .NET 8.0, before I submit a drive-by PR I just wanted to check if there was a reason why MiniScaffold still targeted .NET 6.0?

**Comment by TheAngryByrd** [comment]
Yeah 8 is LTS, let’s do it!

**Comment by simon-reynolds** [comment]
PR opened as #288
