### ISSUE TITLE
Initial build after template installation fails because FAKE package not restored

### ISSUE THREAD

**Issue by rmunn** [TheAngryByrd/MiniScaffold#41]
Linux Mint 18 (based on Ubuntu Xenial), F# 4.1, .Net Core 2.1.4. To reproduce:

1. `dotnet new mini-scaffold -n MyCoolNewLib -lang F#`
2. `cd MyCoolNewLib`
3. `./build.sh`

Result: Paket restore did *not* restore `packages/build/FAKE/tools/FAKE.exe`, so the build naturally failed.

BTW, when I ran `mono .paket/paket.exe -v restore`, Paket said, "Last restore is still up to date". So this might be a Paket bug; I'm still trying to track down why Paket thinks the last restore is still up to date when there's no `packages` folder at all.

**Comment by rmunn** [comment]
The reason is because the file `paket-files/paket.restore.cached` exists in the template. Paket uses that file to do an early exit if there's no work to do: if the `paket.lock` file is identical to `paket-files/paket.restore.cached`, then Paket knows that there's no work to be done and does an early exit to save time.

The template should not include `paket-files/paket.restore.cached` so that a first run of `build.sh` will actually restore the necessary files.

**Comment by TheAngryByrd** [comment]
Derp! This will be easy to fix.  Thanks for the investigation!

**Comment by TheAngryByrd** [comment]
Ok this is fixed.  The only issue you'll run into is https://github.com/TheAngryByrd/MiniScaffold/issues/36
