### ISSUE TITLE
CodeCov support

### ISSUE THREAD

**Issue by TheAngryByrd** [TheAngryByrd/MiniScaffold#50]
## Description

It would be great to have CodeCov support added.  Once Expecto gets support we should add it.  https://github.com/haf/expecto/issues/219.  Here's an example repo doing it in C#/F# https://github.com/codecov/example-csharp/ https://github.com/codecov/example-fsharp

**Comment by TheAngryByrd** [comment]
Here's a dotnet tool with some of this already.  Need to investigate: https://github.com/lucaslorentz/minicover

**Comment by baronfel** [comment]
And now another: https://github.com/tonerdo/coverlet

**Comment by TheAngryByrd** [comment]
I did some investigations https://github.com/haf/expecto/issues/219#issuecomment-374225998 and https://github.com/haf/expecto/issues/219#issuecomment-374810994

I haven't tried https://github.com/tonerdo/coverlet because it's tied to `dotnet test` but the experience looks nice.  Maybe we can apply it to altcover

**Comment by TheAngryByrd** [comment]
Essentially done via https://github.com/TheAngryByrd/MiniScaffold/pull/85

Using altcover and reportgenerator.  If people want to hook up to CodeCov it shouldn't be much work from there.
