### ISSUE TITLE
Unwanted Console.Clear() happens when I run WatchTests, but only on net461 framework target

### ISSUE THREAD

**Issue by rmunn** [TheAngryByrd/MiniScaffold#53]
## Description

When I run `./build.sh WatchTests`, then modify a test file and save it, tests for all three .Net targets (`net461`, `netcore1.1`, and `netcore2.0`) are re-run as they should be. However, the `net461` target causes the terminal to be cleared before Expecto produces its output. Since all three of the targets are run in a non-deterministic order, sometimes this results in the `net461` test running first, in which case all three test results get printed to the newly-cleared console. But sometimes the `net461` test runs second or third, so at least one test result is printed *before* the console is cleared, which is less than desirable. I can still see the test results by scrolling back through the console, but I'd rather get rid of the Console.Clear() behavior entirely.

Now for the strange part, and why I'm reporting this here rather than in the issue tracker(s) for `dotnet-watch`, `dotnet-mono`, or Expecto. If I cd to the `tests/foo.Tests` directory and then run `dotnet watch mono -f net461 -c Release`, then the console-clearing behavior does *not* happen. It only happens if I run the `WatchTests` target from `build.fsx`. If I remove the `netcoreapp1.1` and `netcoreapp2.0` targets from `foo.Tests.fsproj`, so that it's *only* running the `net461` target, then the console-clearing starts happening again. I can only trigger this unwanted behavior via the combination of having `net461` as a target framework in the `.fsproj` file, and running the `WatchTests` target in `build.fsx`.

## To reproduce

1. `dotnet new mini-scaffold -lang F# -n foo -o foo`
1. `cd foo`
1. `./build.sh WatchTests`
1. Edit `tests/foo.Tests/Tests.fs`
1. Add a new test, save the file
1. `dotnet watch` triggers, re-running tests for all three target frameworks
1. Immediately before Expecto starts logging for `net461`, the console is cleared

If `./build.sh WatchTests` is replaced by `cd tests/Foo.Tests && dotnet watch mono -f net461 -c Release`, then the unwanted console-clearing does not occur.

## Error messages, screenshots

After the screen clears, I usually see the characters `070;1R` just before the Expecto log. E.g., at the top of the just-cleared screen, I see the following:

```plaintext
070;1R[17:01:39 INF] EXPECTO? Running tests... <Expecto>
[17:01:39 INF] EXPECTO! 2 tests run in 00:00:00.0902618 – 2 passed, 0 ignored, 0 failed, 0 errored. ᕙ໒( ˵ ಠ ╭͜ʖ╮ ಠೃ ˵ )७ᕗ <Expecto>
[17:01:39 INF] Ended: mono - 16974 <dotnet-mono>
[17:01:39 INF] Handling AssemblyLoadContext Unloading... <dotnet-mono>
[17:01:39 INF] Killing all processes that are created by dotnet-mono and are still running. <dotnet-mono>
watch : Exited
watch : Waiting for a file to change before restarting dotnet...
watch : Started
```

Except that once, it wasn't `070;1R` that printed, but `828;1R` instead:

```plaintext
828;1R[17:13:00 INF] EXPECTO? Running tests... <Expecto>
[17:13:00 INF] EXPECTO! 3 tests run in 00:00:00.0527439 – 3 passed, 0 ignored, 0 failed, 0 errored. ᕙ໒( ˵ ಠ ╭͜ʖ╮ ಠೃ ˵ )७ᕗ <Expecto>
[17:13:00 INF] Ended: mono - 18039 <dotnet-mono>
[17:13:00 INF] Handling AssemblyLoadContext Unloading... <dotnet-mono>
[17:13:00 INF] Killing all processes that are created by dotnet-mono and are still running. <dotnet-mono>
watch : Exited
watch : Waiting for a file to change before restarting dotnet...
```

Those look like VT102 control codes (without the `ESC [` part of the control code) but I haven't been able to find a reference that tells me what `ESC [###;1R` would mean. But this might be a clue that will help track this down.

Note that all the rest of the text appears like it should: the right colors appear in the console output (e.g., in the various parts of Expecto's console logging messages, where certain bits are supposed to be colored blue or green instead of white, they are blue or green as they're supposed to be), so this is not a case where my terminal color codes are malfunctioning. There's just the one unexplained partial code that shows up, and it always shows up immediately **after** the console has been cleared.

## Expected Behavior

I'd like the terminal to *not* be cleared before the `net461` test results are displayed, so that the other test results won't be hidden.

## Known workarounds

I can remove the `net461` framework from the `.fsproj` and just develop for `netcoreapp2.0` for a while, then restore the `net461` framework when I'm ready to run all the tests, which is a good enough workaround for now since I'm still in heavy development of my project and nowhere near releasing. But it would be nice to figure out what's going on.

## Other information

This is on Linux Mint 18, with .Net Core 2.1.4 SDK and Mono 5.8.0.

I've looked through the source for [`dotnet-watch`](https://github.com/aspnet/DotNetTools/tree/dev/src/dotnet-watch) and [`dotnet-mono`](https://github.com/TheAngryByrd/dotnet-mono) and can't find anything that clears the console. I've also looked through the [Expecto source code](https://github.com/haf/expecto) and likewise haven't found any console-clearing code, so it's a bit of a mystery where this interaction is coming from. I'll continue looking, and will post any information I find on this issue.

Feel free to move this over to https://github.com/TheAngryByrd/dotnet-mono if you believe it belongs over there.

**Comment by TheAngryByrd** [comment]
I definitely think this is related to https://github.com/TheAngryByrd/dotnet-mono/issues/31.  I've seen FAKE have similar issues https://github.com/fsharp/FAKE/issues/1213 so I'm guessing I don't have something setup right in there.

**Comment by TheAngryByrd** [comment]
So this  is weird... I tracked it to https://github.com/TheAngryByrd/MiniScaffold/blob/master/Content/build.fsx#L120

If I replace `Console.Readline()` with lets say `Thread.Sleep 100000` I don't get this error.

**Comment by TheAngryByrd** [comment]
I have no clue as to why `Console.Readline()` is causing this.  

Replacing it with something like `let event = Console.CancelKeyPress |> Async.AwaitEvent |> Async.RunSynchronously` seems to fix it and is probably more sane.

**Comment by rmunn** [comment]
I don't know either. I looked through the `Console.Readline` source code for .Net Core, and the only terminal strings I can find that it would print is the string for "move the cursor left one character", which it prints if Backspace is pressed. That's not what's happening here, since I haven't pressed a single key (in *this* terminal window) when the bug triggers.

Maybe there's something going on with locking of some console-related resource? I saw that there was some locking happening in the Console class, but didn't explore that path further. Not sure it's worth spending the time to pursue, either, unless for reasons of idle curiosity. I'll try the `Console.CancelKeyPress |> Async.AwaitEvent |> Async.RunSynchronously` workaround and see if I ever get the bug to trigger via that method.

**Comment by rmunn** [comment]
Yes, using `Console.CancelKeyPress` does seem to work: I've tried multiple times and have never seen this bug trigger when I replaced `Console.ReadLine()` with the `Console.CancelKeyPress` workaround. (This is on the same computer that I was using when I originally triggered this bug.)

So changing the message to "Press Ctrl+C (or Ctrl+Break) to stop..." and then replacing Console.ReadLine() should work.

**Comment by TheAngryByrd** [comment]
I would guess this would be something to with the mono (FAKE) -> dotnet core (dotnet tool) -> mono (theApp).  I've also only noticed it too right after the `mono myapp.exe` part so I'm wondering there's something with the logary facade https://github.com/logary/logary/blob/5173cf2c3b1af1230e053777c56a6ce1327b0cc4/src/Logary.Facade/Facade.fs on mono or Console.Readline on mono.

Ok since that worked I'll make a PR to fix this.  Thanks for much for the deep investigation!

**Comment by rmunn** [comment]
Found the cause, I think. It's a race condition in Mono, caused by a combination of several factors at work:

1. Mono's implementation of Console.ReadLine(), which just calls TermInfoDriver.ReadLine().
2. Mono's implementation of TermInfoDriver.Init().
3. Mono's implementation of TermInfoDriver.GetCursorPosition().
4. The fact that your build script calls Console.ReadLine() *right after* setting up a bunch of asyncs that also use the Console class (because they call DotNetCli.RunCommand(), which prints what it's about to do to the console).

Details if you're interested (I'm recording this mostly for my own sake so that I can make a bug report to the Mono project later):

Mono's Console.ReadLine() implementation actually just calls a "driver" class to do the actual work. There's one driver class per platform it could run on (e.g., one driver class is "WindowsDriver" and one is "TermInfoDriver"), and the one that contains this bug is the TermInfoDriver class that is used on Linux. The [TermInfoDriver.ReadLine() implementation](https://github.com/mono/mono/blob/d2383c037df43eae955add5981cf49fb65176b0d/mcs/class/corlib/System/TermInfoDriver.cs#L1108) first calls TermInfoDriver.Init() if the driver hasn't been initted yet. TermInfoDriver.Init() sets up a bunch of stuff that's not relevant to this bug, and then right at the end it calls GetCursorPosition() so that the driver instance's CursorLeft and CursorTop properties will have meaningful values. If GetCursorPosition() sets the `noGetPosition` field (remember that field, it will be important later) and returns immediately, then Init() will **clear the screen** and set the cursor position to (0,0).

The TermInfoDriver implementation of GetCursorPosition uses terminal escape strings to get the cursor position: it writes `<ESC>[6n` to the terminal, which means [Query Cursor Position](http://www.termsys.demon.co.uk/vtansi.htm). In response, the terminal is supposed to add the sequence `<ESC>[xxx;yyyR` to the *input buffer*, and GetCursorPosition() then starts reading from the terminal's input buffer. (But before it reads, it first checks to make sure that there are any characters available in the input buffer; that check has a **timeout of 1 second** (1000 milliseconds). Remember that timeout, it's the key to this bug.) As GetCursorPosition reads the terminal's input buffer (via a system call), it skips over any characters it doesn't recognize as part of the proper response, since it's quite possible that the user was typing something at the same time that the console printed its response, and you never want to throw away something that could be user input. It's looking for the sequence `<ESC>[###;###R` in the input, where ### is numeric digits. Once it gets that sequence, it sets the CursorLeft and CursorTop properties (technically, it sets their backing fields) with the current X,Y cursor coordinates.

Now, remember that 1-second timeout I mentioned? Well, if that timeout expires without anything showing up in the input buffer, then GetCursorPosition() will set the private Boolean field `noGetPosition` to true, and immediately return. And now you know why I said that that field would be important later: if GetCursorPosition() ends up not finding anything in the terminal's input buffer within 1 second, it gives up waiting and sets that flag. And if it was being called by Init() during the setup process of a new Console instance (which only happens once at the launch of a new process, BTW) then Init() will **clear the screen** so that the cursor position is known to be 0,0.

Now let's look at Console.ReadLine()'s behavior. The thing that ReadLine() does that triggers this bug is quite simple: it merely sits in a `do { ... } while` loop, reading keys from the terminal's input buffer (actually, from stdin, but in this particular case stdin isn't being redirected so it's ultimately reading from the terminal's input buffer) and sticking them in a StringBuilder until it sees a newline character come in. At that point it will exit the do...while loop and return the string it read.

Now, remember how I said that it was important that Console.ReadLine() is the first thing that your build script calls right after setting up a bunch of asyncs that call `dotnet watch`? The reason this bug is triggering is because one of those `dotnet watch` calls ends up starting a Mono process which then starts Expecto. At some point soon after Expecto starts, it is going to call a Console function to start writing to its logs. Since this copy of Expecto is run under Mono, that Console function will in turn end up calling TermInfoDriver.Init(), which will then call GetCursorPosition(). At this point, the key to trigger this bug (which is, in the end, a race condition) is that at some point during that one-second timeout in GetCursorPosition(), the kernel's process scheduler decides to switch over to the FAKE process, which is sitting in a ReadLine() loop eating all the terminal's input buffer — and so GetCursorPosition() doesn't see any input characters, and eventually gives up.

In other words, we get the following sequence of events:

1. The process running FAKE is sitting in Console.ReadLine(), in a `do { ... } while` loop that reads from the terminal's input buffer.
1. A separate process is started that runs Expecto under Mono.
1. That process calls Init(), which calls GetCursorPosition().
1. GetCursorPosition() writes a terminal escape code that causes the terminal to place `<ESC>[70;1R` into the terminal's input buffer because the cursor is currently at line 70, column 1 (in my case; other terminal sizes will produce different numbers).
1. While GetCursorPosition is in a system call with timeout of 1 second, the kernel process scheduler gives control to the FAKE process.
1. FAKE is currently in a ReadLine loop, and ReadLine sees that there is input available, so it grabs the input, emptying out the terminal buffer in the process.
1. The process scheduler goes back to the Expecto process.
1. The 1-second timeout expires, and GetCursorPosition sees no input at the end of that timeout. It therefore gives up and sets `noGetPosition` to true.
1. GetCursorPosition() returns to the Init() call, which sees that `noGetPosition` is true and clears the screen.

So the ultimate culprit is the fact that GetCursorPosition() needs to get input from the terminal, yet the terminal's input is being swallowed by the simultaneously-running ReadLine. Fascinating.

I'll write this up as a bug report for Mono soon.

**Comment by TheAngryByrd** [comment]
Wowwwwwwww. Amazing investigation!

**Comment by rmunn** [comment]
Thanks!
