### ISSUE TITLE
Docs Generation

### ISSUE THREAD

**Issue by TheAngryByrd** [TheAngryByrd/MiniScaffold#62]
## Description

Like project scaffold, it would be nice to have document generation. Need to research more into this.

## Error messages, screenshots

n/a

## Failing test, failing github repo, or reproduction steps

n/a

## Expected Behavior

n/a

## Known workarounds

/na

**Comment by wallymathieu** [comment]
It would probably be easier to use the beta version of FSharp.Formatting if that's what you are after?

**Comment by TheAngryByrd** [comment]
Whatever gives the similar effect to being able to generate some type of documentation website like projectscaffold does.  How that's implemented can be different.

**Comment by baronfel** [comment]
So some compelling reasons to use FSharp.Formatting/FSharp.Literate:

- allows you to use sample scripts as both documentation and tests: [source](https://github.com/fsharp/FSharp.Data/blob/master/docs/content/library/CsvFile.fsx) gets transformed into [docs](https://github.com/fsharp/FSharp.Data/blob/master/docs/content/library/CsvFile.fsx) but are also [integration tests](https://github.com/fsharp/FSharp.Data/blob/master/tests/FSharp.Data.DesignTime.Tests/DocumentationTests.fs#L67-L71)
- generates tooltips for on-hover that contain the types, for better reader comprehension
- allows you to evaluate some code during the build process and inline results, reference them in your docs

There's a really nice step-by-step of a netstandard templating setup that uses fsx/markdown/(fable SSR | giraffe view engine) to generate fully-realized html pages [here](https://thinkbeforecoding.com/post/2018/12/07/full-fsharp-blog#FSharp-Literate)

**Comment by TheAngryByrd** [comment]
Might be worth looking into using https://docute.org/
