### ISSUE TITLE
Start with a benchmarking project too

### ISSUE THREAD

**Issue by TheAngryByrd** [TheAngryByrd/MiniScaffold#76]
## Description

It might be worth considering starting people of right with a BenchmarkDotnet project in the tests folder.  This might people thinking early about trying to benchmark particular parts of their library early on.

## Error messages, screenshots

n/a

## Failing test, failing github repo, or reproduction steps

n/a

**Comment by rmunn** [comment]
An example test using Expecto's `isFasterThan` function (and a test that will clearly pass, like "Function a, which does not call Thread.sleep, is faster than function b which sleeps for 100 milliseconds before returning") might also be a good idea. Get people exposed to the possibilities.

**Comment by TheAngryByrd** [comment]
I'm going to close for now unless someone wants to send a PR for this feature.
