### ISSUE TITLE
dotnet test

### ISSUE THREAD

**Issue by TheAngryByrd** [TheAngryByrd/MiniScaffold#78]
## Description

Now that https://github.com/YoloDev/YoloDev.Expecto.TestSdk/pull/9 has mono support we might be able to just use `dotnet test` instead of `dotnet mono` or `dotnet run`

## Other information

* Operating System:
    - [x] windows [insert version here]
    - [x] macOs [insert version]
    - [x] linux [insert flavor/version here]
* Platform
    - [x] dotnet core
    - [x] dotnet full
    - [x] mono
* Branch or release version:

**Comment by wallymathieu** [comment]
Sweet! 👍
