### ISSUE TITLE
build.fsx getTargetFrameworksFromProjectFile null reference exception

### ISSUE THREAD

**Issue by ScottHutchinson** [TheAngryByrd/MiniScaffold#82]
## Description

If the .fsproj file contains a TargetFramework element instead of a TargetFrameworks element, then running build.cmd results in a null reference exception.

## Error messages, screenshots

https://gist.github.com/ScottHutchinson/beb9fc65b9258d87c5409312469e713c#file-miniscaffold-gettargetframeworksfromprojectfile-null-reference-exception-txt-L86

## Other information

* Operating System:
    - [x] windows [10]
    - [ ] macOs [insert version]
    - [ ] linux [insert flavor/version here]
* Platform
    - [x] dotnet core
    - [ ] dotnet full
    - [ ] mono
* Branch or release version: 0.8.0

**Comment by TheAngryByrd** [comment]
Closed in #83
